_prefs: 
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 4.8849
  - 52.3715
  - 14
description: Streets colored by suffix!
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 14
name: Streets by Suffix!
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
template: ''
